eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10087/eureka/
server:
  port: 11018
spring:
  application:
    name: eurekaclient
  zipkin:
    base-url: http://localhost:9411
  sender:
    #type: rabbit
     type: web
  sleuth:
    sampler:
      percentage: 1.0
      
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    listener: # 这里配置了重试策略
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
   sleuth:
      sampler:
          percentage: 1.0

